site_name: smk's notes
site_description: smk's notes
site_url: https://books.minetest.in/
repo_url: https://github.com/mightyjoe781/notes
repo_name: Github
edit_uri: blob/main/docs/
extra_javascript:
  - src/js/custom.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
extra_css:
  - src/css/custom.css
  - src/css/friendly.css
  - src/css/theme.css
markdown_extensions:
  codehilite:
  mdx_math:
    enable_dollar_delimiter: True #for use of inline $..$
  toc :
    permalink: true
    separator: "_"
plugins:
site_author: smk
copyright: smk
theme:
  name: mkdocs
  custom_dir: overrides
  navigation_depth: 4 
extra:
  analytics:
    provider: google
    property: G-FSJPS15JWH
nav:
  - About: about.md
  - TOC: toc.md

