site_name: smk's notes
site_description: smk's notes
site_url: https://books.minetest.in/
repo_url: https://github.com/mightyjoe781/notes
repo_name: Github
edit_uri: blob/main/docs/
extra_javascript:
  - custom.js
extra_css:
  - css/custom.css
  - css/friendly.css
  - css/theme.css
markdown_extensions:
  toc :
    permalink: true
    separator: "_"
plugins:
site_author: smk
copyright: smk
theme:
  name: mkdocs
  custom_dir: overrides
nav:
  - About: about.md
  - TOC: toc.md
